version: '3.9'

services:
  infra:
    build: .
    volumes:
      - ./gcp:/infrastructure
      - gcloud_config:/root/.config/gcloud
    working_dir: /infrastructure
    entrypoint: bash

volumes:
  gcloud_config: